version: '3.8'

services:
  frontend:
    build: ./FrontEnd
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000

  backend:
    build: ./BackEnd
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - thompson_sampling
    environment:
      - DATABASE_URL=mysql://root:password@mysql/time_db
      - THOMPSON_SAMPLING_URL=http://thompson_sampling:5000

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - mysql_data:/var/lib/mysql

  thompson_sampling:
    build: ./Thomson_Sampling
    ports:
      - "5000:5000"

volumes:
  mysql_data:
    driver: local

networks:
  default:
    driver: bridge
