FROM python:3.10-alpine

ENV PYTHONUNBUFFERED=1

RUN apk update && \
    apk add --no-cache postgresql-dev gcc python3-dev musl-dev bash

ENV PYTHONUNBUFFERED=1


WORKDIR /app


COPY requirements.txt requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
COPY . .
# RUN python main.py
EXPOSE 8000